server:
  port: 8888
  context-path: /app
  
spring:
  thymeleaf:
    prefix: classpath:/templates/  
    suffix: .html
    encoding: UTF-8
    content-type: text/html; charset=utf-8
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#com.mysql.jdbc.Driver